--机器信息表;
CREATE TABLE IF NOT EXISTS t_device
(
	ID BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
	NAME VARCHAR(32) NOT NULL COMMENT '机器名称',
	DEV_NAME VARCHAR(32) NULL DEFAULT NULL COMMENT '机器别名',
	IP_ADDR VARCHAR(32) NOT NULL COMMENT 'ip地址：IPV4',
	USER VARCHAR(32) NOT NULL COMMENT '用户名：SSH/SCP LOGIN USER',
	PORT int(5) NOT NULL COMMENT '端口号：SSH/SCP PORT',
	OS_TYPE VARCHAR(32) NOT NULL COMMENT '操作系统类型',
	STATUS int(2) NOT NULL COMMENT '状态：0-未连接;1-连接成功;2-连接失败',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (ID)
) COMMENT='机器信息表';
--用户信息表
CREATE TABLE IF NOT EXISTS sys_user
(
	ID BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
	name VARCHAR(32) NOT NULL COMMENT '用户名',
	password VARCHAR(100) NOT NULL COMMENT '密码',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (ID)
) COMMENT='用户信息表';