--机器信息表;
CREATE TABLE IF NOT EXISTS t_device
(
	id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
	name VARCHAR(32) NOT NULL COMMENT '机器名称',
	dev_name VARCHAR(32) NULL DEFAULT NULL COMMENT '机器别名',
	ip_addr VARCHAR(32) NOT NULL COMMENT 'ip地址：IPV4',
	user VARCHAR(32) NOT NULL COMMENT '用户名：SSH/SCP LOGIN USER',
	port int(5) NOT NULL COMMENT '端口号：SSH/SCP PORT',
	os_type VARCHAR(32) NOT NULL COMMENT '操作系统类型',
	status int(2) NOT NULL COMMENT '状态：0-未连接;1-连接成功;2-连接失败',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id),
	UNIQUE KEY (ip_addr)
) COMMENT='机器信息表';

--用户信息表
CREATE TABLE IF NOT EXISTS sys_user(
	id BIGINT(20) NOT NULL auto_increment COMMENT '主键ID',
	name VARCHAR(32) NOT NULL COMMENT '用户名',
	password VARCHAR(100) NOT NULL COMMENT '密码',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
	PRIMARY KEY (id),
	UNIQUE KEY (name)
) COMMENT='用户信息表';

-- 系统日志
CREATE TABLE IF NOT EXISTS `sys_log` (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  username varchar(50) COMMENT '用户名',
  operation varchar(50) COMMENT '用户操作',
  method varchar(200) COMMENT '请求方法',
  params varchar(5000) COMMENT '请求参数',
  time bigint NOT NULL COMMENT '执行时长(毫秒)',
  ip varchar(64) COMMENT 'IP地址',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
) COMMENT='系统日志表';