
deploy-center:
  homeDir: X:\deploy\repo
  deployDir: X:\deploy\deploy
  modulesDir: X:\deploy\repo\modules
  scriptsDir: X:\deploy\repo\scripts
  packagesDir: X:\deploy\repo\packages
  logsDir: X:\deploy\repo\logs
  releaseDescFile: release_version.txt
  ftpHost: 192.168.0.72
  ftpPort: 21
  ftpUser: ftp
  ftpPswd: ftp
  ftpRepoDir: /pub/repo
  ftpTempDir: /temp
server:
  port: 9000